### ISSUE TITLE
Not an Issue...

### ISSUE THREAD

**Issue by Jurgenn22** [TazzerMAN/increase_swap_addon#1]
Hi,
Thanks for the addon works great. If possible it would be nice to be able to add the date and time to the logs. So you can actually see when the addon starts and stops. 

Thank you in advance!

**Comment by TazzerMAN** [comment]
Hi,

The latest update (version 1.1.1) now includes the date and time in the logs. This allows you to easily track when the addon starts and stops. 

Thank you for your suggestion :)

Best regards,

**Comment by Jurgenn22** [comment]
@TazzerMAN 
Thanks for the update and the quick response!
