### ISSUE TITLE
Specify whether for Docker, HAOS or Raspbian

### ISSUE THREAD

**Issue by GoodnessJSON** [TazzerMAN/increase_swap_addon#2]
It's not immediately clear in the documentation which OS's are supported. Is this for HAOS?
Thanks for the great work.

**Comment by TazzerMAN** [comment]
Hello,
Yes indeed it is for HAOS. 
I've added this in the README.md 
Thanks for the feedback!

**Comment by GoodnessJSON** [comment]
Amazing thanks for the quick turnaround! This has been an amazing tool.
