### ISSUE TITLE
Swapoff: Invalid Argument

### ISSUE THREAD

**Issue by z-master42** [TazzerMAN/increase_swap_addon#3]
The addon worked well for me. Today, however, I noticed that the errors that I had fixed with the addon had reappeared in my log.
I then noticed that my swap had shrunk back to its original size. When starting the addon, the following error message appears:

```
swapoff: backup/_swap.swap: Invalid argument
```

Unfortunately, I'm not sure whether this was already appearing before. Restarting the host did not help either.

**Comment by TazzerMAN** [comment]
Hi there!

Thanks for the feedback!

I've just updated the addon to 1.1.2. Can you try this new version? If the problem persists could you send me the complete logs of the addon and the host or at least give me a bit more context (lines before and after where you found the error).

Thanks in advance hope it's fixed!

**Comment by z-master42** [comment]
Runs like clockwork. Now the resizing of the swap file also works for me. Thank you for your quick work.
