### ISSUE TITLE
Service gets killed - "Swap file has been already set off"

### ISSUE THREAD

**Issue by emily-pesce** [TazzerMAN/increase_swap_addon#7]
Not sure if this is related to #3 but, I can't get the add-on to continue running. Was fine after initial install, then when rebooted the host this started and won't resolve. (In log below I was trying a different swap size.)

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [16:26:34 28/01/2024] Starting Increase Swap add-on...
> [16:26:34 28/01/2024] Checking swap size at backup...
> [16:26:34 28/01/2024] Resizing swap file: backup/_swap.swap from 500M to 1000M...
> /run.sh: line 65:   103 Killed                  swapoff "${SWAP_FILE}"
> [16:26:39 28/01/2024] Swap file has been already set off. Ignore the previous error line about swapoff Invalid argument.
> **rm: can't remove 'backup/_swap.swap': Operation not permitted**
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by TazzerMAN** [comment]
Hey,

That error about not being able to remove the swap file is tricky. I've got a few quick questions to help sort this out:

1. What version of HAOS are you running?
2. What hardware are you using?
3. Checked the permissions for the `backup` folder and `_swap.swap` file yet?
4. Was the swap file in use when you tried resizing it? `lsof | grep _swap.swap` might tell us.
5. Any special security settings or config in HAOS that could be causing trouble?

Hoping to get this figured out with a bit more info. Thanks for bearing with us!

Cheers!
